apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongo-ui.labels" . | nindent 4 }}
stringData:
  .env: |
    OPENAI_API_KEY=abcdef
    {{- $url := .Values.app.url }}
    {{- $auth := (regexFind "//.*@" $url) | trimPrefix "//" | trimSuffix "@" }}
    {{- $parts := split ":" $auth }}
    MONGOGUI_USERNAME={{ $parts._0 }}
    MONGOGUI_PASSWORD={{ $parts._1 }}
