kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: {{ include "kafka-ui.fullname" . }}
    namespace: {{ .Release.Namespace }}
spec:
    hosts:
      - {{ include "keda.hostname" . }}
    pathPrefixes:
      - "/"
    targetPendingRequests: {{ .Values.targetPendingRequests }}
    scaleTargetRef:
        name: {{ include "kafka-ui.fullname" . }}
        kind: Deployment
        apiVersion: apps/v1
        service: {{ include "kafka-ui.fullname" . }}
        port: {{ .Values.service.port }}
    replicas:
        min: {{ .Values.autoscaling.http.minReplicas }}
        max: {{ .Values.autoscaling.http.maxReplicas }}
