apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbgate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbgate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ ternary "proxy" "http" .Values.authzproxy.enabled }}
      protocol: TCP
      name: http
  selector:
    {{- include "dbgate.selectorLabels" . | nindent 4 }}
