# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pgadmin.fullname" . }}-auth-delegator
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "pgadmin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
