apiVersion: v2
name: mongo-ui
description: mongo-ui Helm chart for Kubernetes
type: application
version: v2025.5.16
appVersion: v2025.5.16
home: https://github.com/kubedb/mongo-gui
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
maintainers:
- name: appscode
  email: support@appscode.com
